### ISSUE TITLE
Joystick activity detected when trying to access OSD

### ISSUE THREAD

**Issue by felleg** [mrchrisster/MiSTer_SAM#181]
I noticed that bringing up the OSD while MiSTer_SAM is doing its thing will delete the SAM tmux session, tmux effectively making SAM think I want to play the current game. Most times, I only access the OSD to change volume or visual settings. I don't want this to make the screensaver halt.

Is there a way to make key detection more nuanced? Something like "> 5 key presses outside of the OSD in the last 10 seconds" would be perfect for me. ;) 

(This feels like such a niche feature request... thanks again for this brilliant set of scripts. MiSTer rules, and this script is part of the reason why!)

**Comment by felleg** [comment]
I also noticed that joystick activity is flagged when buttons are pressed and the OSD is on. If there was a way to fix this, it would be wonderful. Perhaps the same solution could fix this also...

**Comment by mrchrisster** [comment]
Hey Felix, that's an interesting option.

There is a couple ways we could go about this.
The easiest would be to tell the python script for joystick monitoring to only detect a single button, so you can change settings to your liking without disrupting the screensaver.
Unfortunately since we capture the raw button input stream SAM doesn't actually know which button is being pushed so this solution would be different for every SAM user.

What you could do for the moment is set `listenjoy=No` in MiSTer_SAM.ini. This will not interrupt the script for joystick buttons and you can stop it manually by opening MiSTer_SAM_on.sh menu and select stop (or punch a button on a keyboard or move a mouse you have connected)

**Comment by felleg** [comment]
Thanks for reminding me about the `listenjoy=no` option, I think that's a valid compromise for me for now. :) I wish there was an easier way to tackle this without having to buy extra hardware, but I also realize that there are limitations that dictate what SAM can and can't do.

Feel free to close this issue if you want to. Thanks!

**Comment by Paradox** [comment]
Totally a feature that could be added.

**Comment by mrchrisster** [comment]
You can now define buttons for next game and start game through the menu. Recommend way would be to press start and then simply launch SAM from scripts folder again. Otherwise set listenjoy=no
