### ISSUE TITLE
Whitelist support for console cores?

### ISSUE THREAD

**Issue by InquisitiveCoder** [mrchrisster/MiSTer_SAM#90]
It'd be really nice if the SAM .ini file allowed defining whitelists for each console. I prefer to use a specific list of games with SAM since many games don't have interesting attract modes, and all of the workarounds I've found are inconvenient. It seems my only options are:
* blacklist every game I don't want on SAM (which is a longer list than the games I do want, and forces me to update the SAM config every time a new ROM is added)
* move my SAM ROMs into a different folder (not as convenient as having all my ROMs in one place)
* copy my SAM ROMs into a different folder (requires a lot of space for large ROMs like Neo Geo, Sega CD and Turbografx CD) 
* create symlinks (questionable support on exFAT, and requires keeping the symlink targets unzipped)

**Comment by mrchrisster** [comment]
Thanks for your ideas and sorry for the late reply. At this time, neither mellified nor myself have much time to add this feature unfortunately.
 
I know exFAT and symlinks don't sound like a good idea but maybe it's worth a shot. You could create a folder for SAM (eg `/media/fat/Games/SAM` ) and symlink all your favorite games into subfolders. Then you can use the custom path settings in the ini to only have those games displayed. You'd only really need to symlink TGFX16-CD and MegaCD, I would just copy all other roms since they don't take up much space. CHD's should play fine when symlinked.

Another option is to use cifs_mount, linking your samba share to the SAM folder. This way you wouldn't be constrained for space either since you have all the space from your server available. This is what I do currently btw.

If you would like to implement a white list feature yourself, that would obviously be awesome as well. Any help with the project is much appreciated.

**Comment by mrchrisster** [comment]
Hey there,

I thought this might be the easiest way to get in touch. partun is updated and if you update Mister SAM it should dl the newest version (0.1.9)

Cheers,
Christoph

**Comment by InquisitiveCoder** [comment]
Thanks for the heads up!
